import express from 'express';
import Donation from '../models/MockDonation.js';
import Campaign from '../models/Campaign.js';

const router = express.Router();

// ===== TEST ROUTE =====
router.get('/mock-donations/test', (req, res) => {
  res.json({
    success: true,
    message: 'Mock donations route is working!'
  });
});

// ===== GET ALL DONATIONS =====
router.get('/mock-donations', async (req, res) => {
  try {
    const donations = await Donation.find().sort({ createdAt: -1 });
    res.json({
      success: true,
      donations
    });
  } catch (error) {
    console.error('Error fetching donations:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to fetch donations'
    });
  }
});

// ============ PROCESS DONATION ============
router.post('/mock-donations', async (req, res) => {
  console.log('📥 Donation received:', req.body);
  
  try {
    const {
      campaignId,
      donorName,
      donorEmail,
      amount,
      tip = 0,
      paymentMethod,
      isAnonymous = false,
      receiveUpdates = true
    } = req.body;

    // Validate required fields
    if (!campaignId) {
      return res.status(400).json({
        success: false,
        error: 'Campaign ID is required'
      });
    }

    if (!donorEmail) {
      return res.status(400).json({
        success: false,
        error: 'Donor email is required'
      });
    }

    if (!amount || amount <= 0) {
      return res.status(400).json({
        success: false,
        error: 'Valid donation amount is required'
      });
    }

    // Find or create campaign
    let campaign = await Campaign.findById(campaignId);
    if (!campaign) {
      console.log('⚠️ Campaign not found, creating one...');
      campaign = new Campaign({
        _id: campaignId,
        title: 'Test Campaign',
        creator: 'Test Creator',
        creatorInitials: 'TC',
        creatorLocation: 'New York, USA',
        goal: 10000,
        raised: 0,
        donorCount: 0,
        progress: 0,
        daysLeft: 30,
        description: 'Test campaign for donations',
        image: 'https://via.placeholder.com/400x300/059669/ffffff?text=Test+Campaign',
        followers: 0
      });
      await campaign.save();
      console.log('✅ Test campaign created');
    }

    // Calculate total
    const total = Number(amount) + Number(tip);

    // Create donation (IDs will be auto-generated by pre-save hook)
    const donation = new Donation({
      campaignId,
      donorName: isAnonymous ? 'Anonymous' : (donorName || 'Anonymous'),
      donorEmail,
      amount: Number(amount),
      tip: Number(tip),
      total,
      paymentMethod: paymentMethod || 'Google Pay',
      isAnonymous,
      receiveUpdates
    });

    await donation.save();
    console.log('✅ Donation saved:', donation._id);
    console.log('📄 Receipt ID:', donation.receiptId);
    console.log('🔑 Transaction ID:', donation.transactionId);

    // Update campaign
    campaign.raised = (campaign.raised || 0) + Number(amount);
    campaign.donorCount = (campaign.donorCount || 0) + 1;
    if (campaign.goal > 0) {
      campaign.progress = Math.min(Math.round((campaign.raised / campaign.goal) * 100), 100);
    }
    await campaign.save();
    console.log('✅ Campaign updated:', campaign.raised);

    // ===== FIXED: Prepare receipt with ALL required fields =====
    const receipt = {
      receiptId: donation.receiptId || `RCP-${Date.now().toString().slice(-8)}`,
      date: new Date().toLocaleString(),
      transactionId: donation.transactionId || `TXN-${Date.now().toString(36)}-${Math.random().toString(36).substring(2, 6).toUpperCase()}`,
      campaign: {
        title: campaign.title || 'Unknown Campaign',
        creator: campaign.creator || 'Unknown Creator'
      },
      donation: {
        amount: donation.amount || 0,
        tip: donation.tip || 0,
        total: donation.total || 0
      },
      paymentMethod: donation.paymentMethod || 'Google Pay',
      isAnonymous: donation.isAnonymous || false,
      donor: donation.isAnonymous ? 'Anonymous Donor' : (donation.donorName || 'User'),
      // Add these extra fields for better display
      donorEmail: donation.donorEmail,
      campaignId: donation.campaignId,
      status: donation.status || 'completed',
      createdAt: donation.createdAt || new Date()
    };

    console.log('📄 Sending receipt:', receipt);

    res.status(201).json({
      success: true,
      receipt: receipt,
      donationId: donation._id
    });

  } catch (error) {
    console.error('❌ Donation error:', error);
    console.error('Stack:', error.stack);
    res.status(500).json({
      success: false,
      error: error.message || 'Failed to process donation'
    });
  }
});

// ===== GET CAMPAIGN DONATIONS =====
router.get('/mock-donations/campaign/:campaignId', async (req, res) => {
  try {
    const { campaignId } = req.params;
    
    const donations = await Donation.find({ 
      campaignId, 
      status: 'completed' 
    })
    .sort({ createdAt: -1 })
    .limit(20);

    const total = await Donation.countDocuments({ 
      campaignId, 
      status: 'completed' 
    });

    res.json({
      success: true,
      donations,
      total
    });

  } catch (error) {
    console.error('Error fetching donations:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to fetch donations'
    });
  }
});

// ===== GET CAMPAIGN STATS =====
router.get('/mock-donations/stats/:campaignId', async (req, res) => {
  try {
    const { campaignId } = req.params;
    
    const campaign = await Campaign.findById(campaignId);
    if (!campaign) {
      return res.status(404).json({
        success: false,
        error: 'Campaign not found'
      });
    }

    res.json({
      success: true,
      stats: {
        totalRaised: campaign.raised || 0,
        totalDonors: campaign.donorCount || 0,
        progress: campaign.progress || 0
      }
    });

  } catch (error) {
    console.error('Error fetching stats:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to fetch stats'
    });
  }
});

// ===== GET DONATION BY TRANSACTION ID =====
router.get('/mock-donations/transaction/:transactionId', async (req, res) => {
  try {
    const { transactionId } = req.params;
    const donation = await Donation.findOne({ transactionId });
    
    if (!donation) {
      return res.status(404).json({
        success: false,
        error: 'Donation not found'
      });
    }

    res.json({
      success: true,
      donation
    });

  } catch (error) {
    console.error('Error fetching donation:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to fetch donation'
    });
  }
});

export default router;